!> @file rd_commons.f90
!> @brief Global state of RotorDin, formerly held in COMMON blocks.
!>
!> One module per former COMMON block /x/ (module com_x).  Variable
!> names are the canonical (most used) historical names; program units
!> keep their own local names through USE renaming.  Initial values
!> come from the former BLOCK DATA units.
!> Generated by the F2018 migration (tools/pass_commons.py).

module com_bef
  implicit none
  private
  integer, parameter :: mxm = 9
  public :: opf
  character(len=255), save :: opf(mxm)
end module com_bef

module com_blocp
  use rd_kinds, only: lrk
  implicit none
  private
  public :: xursp, yursp, xsymb, ysymb, fac, xwhere, ywhere, xfac, yfac, xver, yver, ldev
  real(lrk), save :: xursp
  real(lrk), save :: yursp
  real(lrk), save :: xsymb
  real(lrk), save :: ysymb
  real(lrk), save :: fac
  real(lrk), save :: xwhere
  real(lrk), save :: ywhere
  real(lrk), save :: xfac
  real(lrk), save :: yfac
  real(lrk), save :: xver
  real(lrk), save :: yver
  integer, save :: ldev
end module com_blocp

module com_brgsm
  use rd_kinds, only: lrk
  implicit none
  private
  public :: mrp
  real(lrk), save :: mrp(2)
  data mrp /0.75_lrk,1.25_lrk/
end module com_brgsm

module com_bstsv
  implicit none
  private
  integer, parameter :: mxm = 9
  public :: lok
  logical, save :: lok(mxm,2)
end module com_bstsv

module com_cab
  implicit none
  private
  character(len=1), parameter :: blank = ' '
  public :: name, descript
  character(len=12), save :: name
  character(len=50), save :: descript
  data name /blank/
  data descript /blank/
end module com_cab

module com_cfm
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxm = 9
  public :: c11, c12, c21, c22, d11, d12, d21, d22, nl
  real(lrk), save :: c11(mxm,3)
  real(lrk), save :: c12(mxm,3)
  real(lrk), save :: c21(mxm,3)
  real(lrk), save :: c22(mxm,3)
  real(lrk), save :: d11(mxm,3)
  real(lrk), save :: d12(mxm,3)
  real(lrk), save :: d21(mxm,3)
  real(lrk), save :: d22(mxm,3)
  integer, save :: nl(mxm)
end module com_cfm

module com_cft
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxm = 9
  public :: eph, eth
  real(lrk), save :: eph(mxm,3)
  real(lrk), save :: eth(mxm,3)
end module com_cft

module com_conc
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxic = 15
  public :: nmic, psic, vlmc, ixic, iyic, izic
  integer, save :: nmic
  real(lrk), save :: psic(mxic)
  real(lrk), save :: vlmc(mxic)
  real(lrk), save :: ixic(mxic)
  real(lrk), save :: iyic(mxic)
  real(lrk), save :: izic(mxic)
  data nmic /0/
  data psic /mxic*0/
  data vlmc /mxic*0/
  data ixic /mxic*0/
  data iyic /mxic*0/
  data izic /mxic*0/
end module com_conc

module com_copcm
  implicit none
  private
  character(len=1), parameter :: blank = ' '
  public :: ops
  character(len=10), save :: ops
  data ops /blank/
end module com_copcm

module com_couplings
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxcplg = 20
  public :: cplgid, cplgst, cplgdp, cplgin, cplgsr, ncplg
  integer, save :: cplgid(mxcplg)
  real(lrk), save :: cplgst(mxcplg)
  real(lrk), save :: cplgdp(mxcplg)
  real(lrk), save :: cplgin(mxcplg)
  real(lrk), save :: cplgsr(mxcplg)
  integer, save :: ncplg
  data ncplg /0/
  data cplgid /mxcplg*0/
  data cplgst /mxcplg*0/
  data cplgdp /mxcplg*0/
  data cplgin /mxcplg*0/
  data cplgsr /mxcplg*0/
end module com_couplings

module com_cpb
  use rd_kinds, only: lrk
  implicit none
  private
  public :: nini, nfin, dw, npi, ncc, imt
  real(lrk), save :: nini
  real(lrk), save :: nfin
  real(lrk), save :: dw
  integer, save :: npi
  integer, save :: ncc
  integer, save :: imt
  data nini /0/
  data nfin /0/
  data dw /0/
  data npi /0/
  data ncc /0/
  data imt /0/
end module com_cpb

module com_cpba
  use rd_kinds, only: lrk
  implicit none
  private
  public :: nrdc, rgini, rgrpm
  integer, save :: nrdc
  real(lrk), save :: rgini
  real(lrk), save :: rgrpm
  data nrdc /0/
  data rgini /0/
  data rgrpm /0/
end module com_cpba

module com_cpbd
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxm = 9
  public :: dmp, nit
  real(lrk), save :: dmp(mxm)
  integer, save :: nit
  data dmp /mxm*0/
  data nit /0/
end module com_cpbd

module com_cpbn
  use rd_kinds, only: lrk
  implicit none
  private
  public :: spdn
  real(lrk), save :: spdn
  data spdn /0/
end module com_cpbn

module com_device
  implicit none
  private
  public :: idev
  integer, save :: idev
end module com_device

module com_dflexi
  implicit none
  private
  integer, parameter :: mxd = 99
  public :: dmodel, dfdofx, dfdofz, nfdisk, nshaftfd
  integer, save :: dmodel(mxd)
  integer, save :: dfdofx(mxd)
  integer, save :: dfdofz(mxd)
  integer, save :: nfdisk
  integer, save :: nshaftfd
  data dmodel /mxd*0/
  data dfdofx /mxd*0/
  data dfdofz /mxd*0/
  data nfdisk /0/
  data nshaftfd /0/
end module com_dflexi

module com_dflexr
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxd = 99
  public :: dkr, df1nd
  real(lrk), save :: dkr(mxd)
  real(lrk), save :: df1nd(mxd)
  data dkr /mxd*0/
  data df1nd /mxd*0/
end module com_dflexr

module com_dis
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxd = 99
  public :: pd, d_d, h_d, rho_d, r2, nd
  real(lrk), save :: pd(mxd)
  real(lrk), save :: d_d(mxd)
  real(lrk), save :: h_d(mxd)
  real(lrk), save :: rho_d(mxd)
  real(lrk), save :: r2(mxd)
  integer, save :: nd
  data pd /mxd*0/
  data d_d /mxd*0/
  data h_d /mxd*0/
  data rho_d /mxd*0/
  data r2 /mxd*0/
  data nd /0/
end module com_dis

module com_disa
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxd = 99
  public :: d_i, i_x, i_y, m_d
  real(lrk), save :: d_i(mxd)
  real(lrk), save :: i_x(mxd)
  real(lrk), save :: i_y(mxd)
  real(lrk), save :: m_d(mxd)
  data d_i /mxd*0/
  data i_x /mxd*0/
  data i_y /mxd*0/
  data m_d /mxd*0/
end module com_disa

module com_divinf
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mtt = 999
  public :: sdv, sde
  real(lrk), save :: sdv(mtt)
  real(lrk), save :: sde(mtt)
end module com_divinf

module com_doff
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxd = 99
  public :: off_d
  real(lrk), save :: off_d(mxd)
  data off_d /mxd*0/
end module com_doff

module com_dsc
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxd = 99
  public :: md, idx, idy
  real(lrk), save :: md(mxd)
  real(lrk), save :: idx(mxd)
  real(lrk), save :: idy(mxd)
  data md /mxd*0/
  data idx /mxd*0/
  data idy /mxd*0/
end module com_dsc

module com_eix
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxs = 99
  public :: l, d, di, ps, e, nu, rho_e, g_e, r1, cs
  real(lrk), save :: l
  real(lrk), save :: d(mxs)
  real(lrk), save :: di(mxs)
  real(lrk), save :: ps(mxs)
  real(lrk), save :: e(mxs)
  real(lrk), save :: nu(mxs)
  real(lrk), save :: rho_e(mxs)
  real(lrk), save :: g_e(mxs)
  real(lrk), save :: r1(mxs)
  integer, save :: cs
  data l /0/
  data d /mxs*0/
  data di /mxs*0/
  data ps /mxs*0/
  data e /mxs*0/
  data nu /mxs*0/
  data rho_e /mxs*0/
  data g_e /mxs*0/
  data r1 /mxs*0/
  data cs /0/
end module com_eix

module com_eix2
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxs = 99
  public :: ys
  real(lrk), save :: ys(mxs)
  data ys /mxs*0/
end module com_eix2

module com_eixa
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxs = 99
  public :: divs, umps
  integer, save :: divs(mxs)
  real(lrk), save :: umps(mxs)
  data divs /mxs*0/
  data umps /mxs*0/
end module com_eixa

module com_eixshape
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxs = 99
  public :: d2, di2, etype
  real(lrk), save :: d2(mxs)
  real(lrk), save :: di2(mxs)
  integer, save :: etype(mxs)
  data d2 /mxs*0/
  data di2 /mxs*0/
  data etype /mxs*0/
end module com_eixshape

module com_elkind
  implicit none
  private
  integer, parameter :: ekmx = 16
  public :: ekid
  integer, save :: ekid(ekmx)
  data ekid /1,2,3,4,5,6,7,8,9,10,11,12,13,0,14,15/
end module com_elkind

module com_emsgs
  implicit none
  private
  integer, parameter :: mxg1 = 35
  public :: emsg
  character(len=50), save :: emsg(mxg1)
  data emsg /'unable to open file','file not found','error reading','out of bounds','index out of bounds', &
    & 'invalid option','too/few data','invalid data ','support without mass','speed increment<=0', &
    & 'invalid speed range','ZGGEVX report error','error writing','position not found','position not defined', &
    & 'time function eval @','UMP defined more than once','no excitation','critical speed not found', &
    & 'section division','section count','invalid speed','ZGETRF report error','no convergence', &
    & 'nothing to be done...','invalid directory','invalid index','DGETRF report error','time not strictly periodic', &
    & 'no time transient data','matrix is singular','DGETRS report error','unable to determine','no suitable bearing', &
    & 'already defined'/
end module com_emsgs

module com_epm
  use rd_kinds, only: lrk, wp
  implicit none
  private
  integer, parameter :: mte = 1000
  public :: fi, fn, avl, ddm
  complex(wp), save :: fi(mte,mte)
  real(lrk), save :: fn(mte)
  complex(wp), save :: avl(mte)
  integer, save :: ddm
end module com_epm

module com_epm1
  use rd_kinds, only: wp
  implicit none
  private
  integer, parameter :: mte = 1000
  public :: psi
  complex(wp), save :: psi(mte,mte)
end module com_epm1

module com_epmq
  use rd_kinds, only: wp
  implicit none
  private
  integer, parameter :: mtq = 1000
  public :: modal_condition, modal_valid
  real(wp), save :: modal_condition(mtq)
  logical, save :: modal_valid(mtq)
end module com_epmq

module com_eqvlen
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxs = 99
  integer, parameter :: mtt = 999
  integer, parameter :: mts = 999
  public :: teql, tsl
  real(lrk), save :: teql(mxs)
  real(lrk), save :: tsl(mtt)
  data teql /mxs*0/
  data tsl /mtt*0/
end module com_eqvlen

module com_exgeo
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: npgx = 999
  integer, parameter :: npix = 9
  integer, parameter :: nppx = npgx*npix
  public :: cc, ik, cx, cy, mxx, mnx, last
  integer, save :: cc(npgx)
  integer, save :: ik(npgx)
  real(lrk), save :: cx(npgx,npix)
  real(lrk), save :: cy(npgx,npix)
  real(lrk), save :: mxx
  real(lrk), save :: mnx
  integer, save :: last
  data mxx /0/
  data mnx /0/
  data cc /npgx*0/
  data ik /npgx*0/
  data last /0/
  data cx /nppx*0/
  data cy /nppx*0/
end module com_exgeo

module com_fbn
  implicit none
  private
  public :: bsn
  character(len=128), save :: bsn
end module com_fbn

module com_fillets
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxtfil = 20
  public :: ntfil, tfilid, tfilrd
  integer, save :: ntfil
  integer, save :: tfilid(mxtfil)
  real(lrk), save :: tfilrd(mxtfil)
  data ntfil /0/
  data tfilid /mxtfil*0/
  data tfilrd /mxtfil*0.0_lrk/
end module com_fillets

module com_fixstif
  use rd_kinds, only: lrk
  implicit none
  private
  public :: fxstf
  real(lrk), save :: fxstf
  data fxstf /0/
end module com_fixstif

module com_fndctl
  implicit none
  private
  public :: factive, fcompare, fndof, fnint, fdkind
  logical, save :: factive
  logical, save :: fcompare
  integer, save :: fndof
  integer, save :: fnint
  integer, save :: fdkind
  data factive /.false./
  data fcompare /.false./
  data fndof /0/
  data fnint /0/
  data fdkind /0/
end module com_fndctl

module com_fnddynf
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxfpt = 2048
  public :: fdfreq
  real(lrk), save :: fdfreq(mxfpt)
end module com_fnddynf

module com_fnddyni
  implicit none
  private
  public :: fdmodel, fdnpt
  integer, save :: fdmodel
  integer, save :: fdnpt
end module com_fnddyni

module com_fnddynz
  use rd_kinds, only: wp
  implicit none
  private
  integer, parameter :: mxfpt = 2048
  public :: fdz
  complex(wp), save :: fdz(10,mxfpt)
end module com_fnddynz

module com_fndifc
  implicit none
  private
  integer, parameter :: mxi = 20
  public :: ficonn, fiidx, fixd, fizd
  integer, save :: ficonn(mxi)
  integer, save :: fiidx(mxi)
  integer, save :: fixd(mxi)
  integer, save :: fizd(mxi)
  data ficonn /mxi*0/
  data fiidx /mxi*0/
  data fixd /mxi*0/
  data fizd /mxi*0/
end module com_fndifc

module com_fndmat
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mtg = 500
  public :: fm, fk, fc
  real(lrk), save :: fm(mtg,mtg)
  real(lrk), save :: fk(mtg,mtg)
  real(lrk), save :: fc(mtg,mtg)
end module com_fndmat

module com_fndmod
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mtg = 500
  integer, parameter :: mxf = 500
  public :: fzeta
  real(lrk), save :: fzeta(mtg)
  data fzeta /mxf*0.0_lrk/
end module com_fndmod

module com_fndray
  use rd_kinds, only: lrk
  implicit none
  private
  public :: falpha, fbeta
  real(lrk), save :: falpha
  real(lrk), save :: fbeta
  data falpha /0.0_lrk/
  data fbeta /0.0_lrk/
end module com_fndray

module com_fndstr
  implicit none
  private
  public :: ffile, fred
  character(len=255), save :: ffile
  character(len=16), save :: fred
  data ffile /' '/
  data fred /'USER_REDUCED'/
end module com_fndstr

module com_fnm
  implicit none
  private
  integer, parameter :: onmx = 17
  public :: onm, mtx
  character(len=8), save :: onm(onmx)
  character(len=8), save :: mtx(6)
  data onm(1) /'_md'/
  data onm(2) /'_cp'/
  data onm(3) /'_ur'/
  data onm(4) /'_tr'/
  data onm(5) /'_ou'/
  data onm(6) /'_lg'/
  data onm(7) /'_nd'/
  data onm(8) /'_el'/
  data onm(9) /'_sl'/
  data onm(10) /'_sm'/
  data onm(11) /'_am'/
  data onm(12) /'_bs'/
  data onm(13) /'_bp'/
  data onm(14) /'_ei'/
  data onm(15) /'_hr'/
  data onm(16) /'_ti'/
  data onm(17) /'_ft'/
  data mtx /'_re-phi','_im-phi','_re-psi','_im-psi','_re-lam','_im-lam'/
end module com_fnm

module com_frax
  implicit none
  private
  public :: fzax
  logical, save :: fzax(2)
  data fzax /2*.false./
end module com_frax

module com_grids
  implicit none
  private
  public :: hgrid, vgrid
  logical, save :: hgrid
  logical, save :: vgrid
  data hgrid /.true./
  data vgrid /.true./
end module com_grids

module com_gycsedc
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxgc = 5
  public :: gycsedid, gycsedvl, ngycsed
  integer, save :: gycsedid(mxgc)
  real(lrk), save :: gycsedvl(mxgc)
  integer, save :: ngycsed
  data gycsedid /mxgc*0/
  data gycsedvl /mxgc*0/
  data ngycsed /0/
end module com_gycsedc

module com_hang
  use rd_kinds, only: lrk
  implicit none
  private
  character(len=1), parameter :: blank = ' '
  public :: hangle, accg, isf, ha
  real(lrk), save :: hangle
  real(lrk), save :: accg
  integer, save :: isf(2)
  character(len=10), save :: ha
  data hangle /0/
  data accg /0/
  data isf /2*1/
  data ha /blank/
end module com_hang

module com_hmsgs
  implicit none
  private
  integer, parameter :: mxg4 = 30
  public :: hmsg
  character(len=50), save :: hmsg(mxg4)
  data hmsg /' : undamped angular critical speed map(l)',' : include bearing support stiffness(l)', &
    & ' : Campbell diagram(l,t) and stability map(l)',' : export FE geometry',' : unbalance(l)/frequency(t) response', &
    & ' : show this help',' : speed var bearing params(l)',' : undamped critical speed map(l)', &
    & ' : generates an operational log',' : modal shapes',' : time transient(t)', &
    & ' : <file*> override/<d>ump messages',' : output HPGL plot (if available)',' : flexural-torsion analysis(t)', &
    & ' : static(t) elastic line(l)',' : time(l) orbits and shape/harmonic(t) response',' : check current version', &
    & ' : <HB/mm> export plain<Harwell-Boeing/mat.market>',' : <file*> define input <file> name', &
    & ' : <folder*> define output(/input) <folder> name',' : <file*> <b/s/t> input <bea/sup/tor> <file> mask', &
    & ' : use standard i/o and error (wo files)',' ',' ',' command line arguments (case sensitive):', &
    & ' <optional>, *not -std, avail:(l)ateral (t)orsion','version request.','help request.','file generated', &
    & 'messages dump.'/
end module com_hmsgs

module com_htrc
  implicit none
  private
  public :: ctr
  character(len=19), save :: ctr
end module com_htrc

module com_inf
  implicit none
  private
  public :: vrs, dta, rgh, sid
  character(len=4), save :: vrs
  character(len=4), save :: dta
  character(len=32), save :: rgh
  character(len=32), save :: sid
  data dta /'2021'/
  data vrs /'1.10'/
  data sid /' Rotordynamic Calculations'/
  data rgh /' WEG Equipamentos Eletricos S.A.'/
end module com_inf

module com_inm
  implicit none
  private
  public :: ein
  character(len=128), save :: ein
  data ein /'rotordin.in'/
end module com_inm

module com_kasc
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: lmts = 999
  public :: vkasc
  real(lrk), save :: vkasc(lmts)
end module com_kasc

module com_knd
  implicit none
  private
  character(len=1), parameter :: blank = ' '
  public :: cknd, supr
  character(len=1), save :: cknd
  character(len=1), save :: supr
  data cknd /blank/
  data supr /blank/
end module com_knd

module com_lgf
  implicit none
  private
  public :: ilg
  integer, save :: ilg
  data ilg /0/
end module com_lgf

module com_lid
  implicit none
  private
  public :: nre, lne
  integer, save :: nre
  character(len=199), save :: lne(18)
  data nre /18/
  data lne /'NAME','DESCRIPTION', &
    & 'SECTIONS  LENGTH    DIV       MXDIV     LDR       HANGLE    ACCG      HANUN     SHMFWD', &
    & 'POSITION  EXTDIAM   INTDIAM   YOUNG     POISSON   DENSITY   DIV       UMP       YELD STR', &
    & 'DISK      NRAT      GYCOF', &
    & 'POSITION  DIAMETER  LENGTH    DENSITY   INTDIAM   IX        IY        WEIGHT    OFFSET', &
    & 'BEARING   SCALE     RKS       FXSTF', &
    & 'POSITION  KXX       KXZ       KZZ       KZX       CXX       CXZ       CZZ       CZX       WEIGHT    KPH       K&
    &TH','CPBIS     CPBFS     CPBSPD    NCRSPD    INTSPD    SMIST     SMNDC     SMSPD     IMDTRK', &
    & 'EXCT      UNBIS     UNBFS     UNBSPD    UNBMD     MINAMP    MDRPM     EANUN', &
    & 'POSITION  VALUE     PHASE     KIND      THF/OFS', &
    & 'RESPPOS   NBRMOD    TIMOEP    TIMSPD    TANGLE     RANUN     TAUN','POSITION  DISPL     ORIENT','OPTIONS', &
    & 'CONCENT','CMASSPOS  CMASS     IX        IY        IZ','SUPPORT   SCALE', &
    & 'BEANBR    KXX       KXZ       KZZ       KZX       CXX       CXZ       CZZ       CZX       WEIGHT    DESC'/
end module com_lid

module com_lif
  implicit none
  private
  public :: usr, dtu, tmu
  character(len=12), save :: usr
  character(len=10), save :: dtu
  character(len=10), save :: tmu
end module com_lif

module com_lio
  implicit none
  private
  public :: nro, lno
  integer, save :: nro
  character(len=99), save :: lno(4)
  data nro /4/
  data lno /'KIND      MODES','BEAFILES  MINAMP    MDRPM     CPBCRX','BEANBR    BEAFILES','OPTIONS'/
end module com_lio

module com_lis
  implicit none
  private
  public :: nrs, lns
  integer, save :: nrs
  character(len=104), save :: lns(2)
  data nrs /2/
  data lns /'SUPPORT', &
    & 'BEANBR    KXX       KXZ       KZZ       KZX       CXX       CXZ       CZZ       CZX       WEIGHT    DESC'/
end module com_lis

module com_lit
  implicit none
  private
  public :: nrt, lnt
  integer, save :: nrt
  character(len=72), save :: lnt(12)
  data nrt /12/
  data lnt /'KIND','CPNRT     CPSM      CPSP','COUPL     FPRT      FPRTS     MODES', &
    & 'CINX      KC        DC        IC        RATIO','DAMPING   MD_OFF    ETYPE     FRLGAP    FRQRD', &
    & 'MODE      RATIO','FILLET    SHSTR     STEQSF','FIDX      RADIUS', &
    & 'TRANS     ITSTP     RSSTP     SIZE      INIT      FINT','DAMPING','TRANSIENT DATA','OPTIONS'/
end module com_lit

module com_lot
  implicit none
  private
  public :: nro, lno
  integer, save :: nro
  character(len=72), save :: lno(5)
  data nro /5/
  data lno /'FTCNP     FTNBCY    FTSTPK    FTASM     SCLST','SCUSTL','FTSCSF', &
    & 'KEYS      ALTQP     MXTQP     TQSTF     BDSTF     NTIND', &
    & 'KIDX      DIST      HEIGHT    LENGTH    RF        WIDTH     RG'/
end module com_lot

module com_lset
  use rd_kinds, only: lrk
  implicit none
  private
  public :: vm, dl, vx
  real(lrk), save :: vm(2)
  real(lrk), save :: dl(2)
  real(lrk), save :: vx(2)
end module com_lset

module com_man
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxm = 9
  public :: kxx, kxz, kzz, kzx, cxx, cxz, czz, czx, mm, sc
  real(lrk), save :: kxx(mxm)
  real(lrk), save :: kxz(mxm)
  real(lrk), save :: kzz(mxm)
  real(lrk), save :: kzx(mxm)
  real(lrk), save :: cxx(mxm)
  real(lrk), save :: cxz(mxm)
  real(lrk), save :: czz(mxm)
  real(lrk), save :: czx(mxm)
  real(lrk), save :: mm(mxm)
  real(lrk), save :: sc
  data kxx /mxm*0/
  data kxz /mxm*0/
  data kzz /mxm*0/
  data kzx /mxm*0/
  data cxx /mxm*0/
  data cxz /mxm*0/
  data czz /mxm*0/
  data czx /mxm*0/
  data mm /mxm*0/
  data sc /0/
end module com_man

module com_markkd
  implicit none
  private
  public :: mxmark
  integer, save :: mxmark
  data mxmark /6/
end module com_markkd

module com_mat
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mtg = 500
  public :: mm, mg, dm, smn
  real(lrk), save :: mm(mtg,mtg)
  real(lrk), save :: mg(mtg,mtg)
  integer, save :: dm
  integer, save :: smn
end module com_mat

module com_maudf
  use rd_kinds, only: lrk
  implicit none
  private
  public :: audit_suspect, audit_pivot
  integer, save :: audit_suspect
  real(lrk), save :: audit_pivot
end module com_maudf

module com_maudi
  implicit none
  private
  public :: mesh_modes, mesh_levels
  integer, save :: mesh_modes
  integer, save :: mesh_levels
  data mesh_modes /4/
  data mesh_levels /3/
end module com_maudi

module com_maudl
  implicit none
  private
  public :: mesh_en, refm_set, refcg_set
  logical, save :: mesh_en
  logical, save :: refm_set
  logical, save :: refcg_set
  data mesh_en /.false./
  data refm_set /.false./
  data refcg_set /.false./
end module com_maudl

module com_maudr
  use rd_kinds, only: lrk
  implicit none
  private
  public :: mesh_tol, ref_mass, ref_cg
  real(lrk), save :: mesh_tol
  real(lrk), save :: ref_mass
  real(lrk), save :: ref_cg
  data mesh_tol /0.005_lrk/
  data ref_mass /0.0_lrk/
  data ref_cg /0.0_lrk/
end module com_maudr

module com_mbk
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mtg = 500
  public :: mkb
  real(lrk), save :: mkb(mtg,mtg)
end module com_mbk

module com_mdamps
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxtdmp = 10
  public :: tdmrt, tdmmd, ntdmp
  real(lrk), save :: tdmrt(mxtdmp)
  integer, save :: tdmmd(mxtdmp)
  integer, save :: ntdmp
  data tdmrt /mxtdmp*0/
  data tdmmd /mxtdmp*0/
  data ntdmp /0/
end module com_mdamps

module com_mdampso
  implicit none
  private
  public :: mdoff
  integer, save :: mdoff
  data mdoff /0/
end module com_mdampso

module com_mdd
  use rd_kinds, only: lrk
  implicit none
  private
  public :: qtd_modos, porb, rorb, rang
  integer, save :: qtd_modos
  real(lrk), save :: porb
  real(lrk), save :: rorb
  real(lrk), save :: rang
  data qtd_modos /0/
  data porb /0/
  data rorb /0/
  data rang /0/
end module com_mdd

module com_mdd1
  implicit none
  private
  character(len=1), parameter :: blank = ' '
  public :: ru
  character(len=10), save :: ru(2)
  data ru /2*blank/
end module com_mdd1

module com_mdd2
  implicit none
  private
  integer, parameter :: xmd = 19
  public :: imd, nsm
  integer, save :: imd(xmd)
  integer, save :: nsm
  data imd /xmd*0/
  data nsm /0/
end module com_mdd2

module com_mfa
  use rd_kinds, only: lrk
  implicit none
  private
  character(len=1), parameter :: blank = ' '
  public :: ma, rm, au
  real(lrk), save :: ma
  real(lrk), save :: rm
  character(len=10), save :: au
  data ma /0/
  data rm /0/
  data au /blank/
end module com_mfa

module com_mmmsg
  implicit none
  private
  integer, parameter :: mxg0 = 15
  public :: exmsg
  character(len=50), save :: exmsg(mxg0)
  data exmsg /'prtmt:general i/o error','mm_comment_write:general i/o error','mm_header_check:illegal id', &
    & 'mm_header_check:illegal type','mm_header_check:illegal rep','mm_header_check:illegal field', &
    & 'mm_header_check:illegal symm','mm_header_write:general i/o error','mm_size_write:general i/o error', &
    & 'mm_values_write:general i/o error','dwritehb:dnscsr,dense to sparse','dwritehb:no elements,only zeros', &
    & 'dwritepl:general i/o error','export:invalid job id',' '/
end module com_mmmsg

module com_msb
  implicit none
  private
  integer, parameter :: mxlg = 20
  public :: lid, msl
  integer, save :: lid
  character(len=80), save :: msl(mxlg)
end module com_msb

module com_mtk
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mtg = 500
  public :: mk1
  real(lrk), save :: mk1(mtg,mtg)
end module com_mtk

module com_nbc
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxm = 9
  public :: cp, scl, bc
  integer, save :: cp
  real(lrk), save :: scl(mxm)
  real(lrk), save :: bc(mxm)
  data cp /0/
  data bc /mxm*0/
  data scl /mxm*0/
end module com_nbc

module com_nmi
  implicit none
  private
  public :: inm, sbv
  character(len=8), save :: inm
  character(len=2), save :: sbv
  data sbv /'-0'/
  data inm /'RotorDin'/
end module com_nmi

module com_opt
  implicit none
  private
  public :: std
  logical, save :: std
end module com_opt

module com_otho
  implicit none
  private
  integer, parameter :: joop = 7
  public :: oopt
  character(len=1), save :: oopt(joop)
  data oopt /'h','l','v','i','d','g','o'/
end module com_otho

module com_pmk
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxm = 9
  integer, parameter :: mpm = 99
  public :: nt, kmc, cmc, rmc
  integer, save :: nt(mxm)
  real(lrk), save :: kmc(mxm,mpm,4)
  real(lrk), save :: cmc(mxm,mpm,4)
  real(lrk), save :: rmc(mxm,mpm)
end module com_pmk

module com_pmrk
  implicit none
  private
  public :: imerk
  integer, save :: imerk
  data imerk /0/
end module com_pmrk

module com_pmsgs
  implicit none
  private
  integer, parameter :: mxg3 = 70
  public :: pmsg
  character(len=50), save :: pmsg(mxg3)
  data pmsg /'      speed (rpm)','   frequency (Hz)','Campbell Diagram','log dec.','Stability Map', &
    & 'first eigenvalue:','Damped Unbalance Response','angle (rad)','angle (deg)','length (m)','Static Elastic Line', &
    & 'Composite Displacement x-z','Undamped Critical Speed Map','radial stiffness (N/m)', &
    & 'Ang. Und. Critical Speed Map','angular stiffness (N/rad)','with gyroscopic effect','speed (rpm)','hor.stiff', &
    & 'vert.stiff','diameter (mm)','Shaft Elements Geometry','center of mass(x, mm)','Mode Shape', &
    & 'Displacement Orbit','x (m)','z (m)','Displacement Shape','Time Displacement Shape','Displacement Amp.', &
    & '   stiffness (N/m)','Stiffness on Bearing #','Damping on Bearing #','   damping (N/m/s)', &
    & '   Torsion Mode Shape','mode:    Hz','Static Torsion Stress',' id    Stress (Pa)','Tors.Freq.Resp.-Amplitude', &
    & 'Tors.Freq.Resp.-Angle','tot.ang.displ.(deg)','Tors. Campbell Diagram ','Torsion Steady-State','time (s)', &
    & 'input torque (Nm)','y (m)','Torsion Time Transient','div.torque (Nm)','input data','tot.ang.disp.(rad)', &
    & 'div.ang.disp.(rad)','Tors.Freq.Resp.-Torque','div.ang.disp.(deg)','rel.ang.disp.','Tors.Freq.Resp.-Sh.Stress', &
    & 'div.sh.stress (Pa)','num.int:','Bending moment (Nm)','Shear Force (N)','Median filter width (1=no):', &
    & 'length (mm)','modes','max. (m)','rated (rpm)','Bending Stress (MPa)','supp=','Amplitude (m)',' ',' ',' '/
end module com_pmsgs

module com_pmt
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxm = 9
  integer, parameter :: mpm = 99
  public :: tph, tth
  real(lrk), save :: tph(mxm,mpm)
  real(lrk), save :: tth(mxm,mpm)
end module com_pmt

module com_ppr
  implicit none
  private
  integer, parameter :: mop = 20
  character(len=1), parameter :: blank = ' '
  public :: opt, ifn
  logical, save :: opt(mop)
  character(len=255), save :: ifn
  data opt /mop*.false./
  data ifn /blank/
end module com_ppr

module com_progress_cfg
  use rd_kinds, only: lrk
  implicit none
  private
  public :: pgstd, pgon, pglast, pgstart, pgname
  logical, save :: pgstd
  logical, save :: pgon
  integer, save :: pglast(24)
  real(lrk), save :: pgstart(24)
  character(len=32), save :: pgname(24)
  data pgstd /.false./
  data pgon /.false./
  data pglast /24*-1/
  data pgstart /24*0.0_lrk/
  data pgname /24*' '/
end module com_progress_cfg

module com_pscale
  use rd_kinds, only: lrk
  implicit none
  private
  public :: xsn, ysn
  real(lrk), save :: xsn(2)
  real(lrk), save :: ysn(2)
  data xsn /2*1/
  data ysn /2*1/
end module com_pscale

module com_pse
  implicit none
  private
  public :: v_maior, v_menor
  integer, save :: v_maior
  integer, save :: v_menor
  data v_maior /0/
  data v_menor /0/
end module com_pse

module com_psea
  use rd_kinds, only: lrk
  implicit none
  private
  public :: ld_r
  real(lrk), save :: ld_r
  data ld_r /0/
end module com_psea

module com_pst
  implicit none
  private
  public :: wrl
  character(len=255), save :: wrl
end module com_pst

module com_scmsg
  implicit none
  private
  integer, parameter :: nsmsg = 30
  public :: lmc
  character(len=10), save :: lmc(nsmsg)
  data lmc /' input   :',' data    :',' output  :',' matrix  :',' cmpbl fv:',' cmpbl   :',' crt. map:',' act. map:', &
    & ' modspc  :',' modspc v:',' modes   :',' resp_d  :',' resp_t  :',' resp_dv :',' resp_tv :',' geom exp:', &
    & ' elas lin:',' export  :',' export v:',' bear par:',' t.matrix:',' t.modspc:',' t.campbl:',' t. modes:', &
    & ' t.resp_f:',' t.resp_h:',' t.tm_int:',' t.static:',' init    :',' t.flxtor:'/
end module com_scmsg

module com_scmsg1
  implicit none
  private
  public :: msz
  character(len=8), save :: msz
  data msz /'$m size '/
end module com_scmsg1

module com_sea
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mts = 999
  public :: rs, es, gs, dely, s, ie, ump
  real(lrk), save :: rs(mts)
  real(lrk), save :: es(mts)
  real(lrk), save :: gs(mts)
  real(lrk), save :: dely(mts)
  real(lrk), save :: s(mts)
  real(lrk), save :: ie(mts)
  real(lrk), save :: ump(mts)
  data rs /mts*0/
  data es /mts*0/
  data gs /mts*0/
  data dely /mts*0/
  data s /mts*0/
  data ie /mts*0/
  data ump /mts*0/
end module com_sea

module com_seaf
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mts = 999
  public :: dfc, dfa
  real(lrk), save :: dfc(mts)
  real(lrk), save :: dfa(mts)
  data dfc /mts*0/
  data dfa /mts*0/
end module com_seaf

module com_sec
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mts = 999
  public :: n, y, nt, nn
  real(lrk), save :: n(mts)
  real(lrk), save :: y(mts)
  integer, save :: nt
  integer, save :: nn
  data nt /0/
  data nn /0/
  data n /mts*0/
  data y /mts*0/
end module com_sec

module com_sed
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mts = 999
  public :: ds, di_d, di_s
  real(lrk), save :: ds(mts+1)
  real(lrk), save :: di_d(mts)
  real(lrk), save :: di_s(mts)
end module com_sed

module com_seg
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mts = 999
  public :: gfc
  real(lrk), save :: gfc(mts)
end module com_seg

module com_skaset
  implicit none
  private
  public :: isset
  logical, save :: isset(2)
end module com_skaset

module com_sp1
  implicit none
  private
  integer, parameter :: mxm = 9
  public :: ns, bn
  integer, save :: ns
  integer, save :: bn(mxm)
  data ns /0/
  data bn /mxm*0/
end module com_sp1

module com_sp2
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxm = 9
  integer, parameter :: imx = 9*mxm
  public :: sup, sps
  real(lrk), save :: sup(mxm,9)
  real(lrk), save :: sps
  data sup /imx*0/
  data sps /0/
end module com_sp2

module com_sp3
  implicit none
  private
  integer, parameter :: mxm = 9
  character(len=1), parameter :: blank = ' '
  public :: kos
  character(len=10), save :: kos(mxm)
  data kos /mxm*blank/
end module com_sp3

module com_sprat
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mtt = 999
  integer, parameter :: mts = 999
  public :: crat
  real(lrk), save :: crat(mtt)
  data crat /mtt*0/
end module com_sprat

module com_sprat1
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mtt = 999
  public :: csrt
  real(lrk), save :: csrt(mtt)
end module com_sprat1

module com_sprat2
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mtt = 999
  public :: gsst
  real(lrk), save :: gsst(mtt)
end module com_sprat2

module com_sta
  implicit none
  private
  public :: stm
  character(len=36), save :: stm
end module com_sta

module com_tcoup
  implicit none
  private
  integer, parameter :: mtt = 999
  public :: idsec, cnsc
  integer, save :: idsec(mtt)
  integer, save :: cnsc
end module com_tcoup

module com_tcpbl
  use rd_kinds, only: lrk
  implicit none
  private
  public :: tcpn, tsmg, nteln
  real(lrk), save :: tcpn
  real(lrk), save :: tsmg
  integer, save :: nteln
  data tcpn /0/
  data tsmg /0/
  data nteln /0/
end module com_tcpbl

module com_tcpbl1
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxteln = 15
  public :: teln
  real(lrk), save :: teln(mxteln)
  data teln /mxteln*0/
end module com_tcpbl1

module com_tdmp
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mtg = 500
  integer, parameter :: mtx = mtg*mtg
  public :: tcp
  real(lrk), save :: tcp(mtg,mtg)
  data tcp /mtx*0/
end module com_tdmp

module com_tepm
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mtg = 500
  integer, parameter :: mtx = mtg*mtg
  public :: rfi, rlam, ddm
  real(lrk), save :: rfi(mtg,mtg)
  real(lrk), save :: rlam(mtg)
  integer, save :: ddm
  data rfi /mtx*0/
  data rlam /mtg*0/
  data ddm /0/
end module com_tepm

module com_tflxtor
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxscls = 20
  integer, parameter :: mxsclsx = 6*mxscls
  public :: siv, nsi, nki, sfv, ftv, scy, tvl, kvl, nsc, nks, nnt
  integer, save :: siv(mxscls)
  integer, save :: nsi(mxscls)
  integer, save :: nki(mxscls)
  integer, save :: sfv(mxscls)
  real(lrk), save :: ftv(4)
  real(lrk), save :: scy(mxscls)
  real(lrk), save :: tvl(4)
  real(lrk), save :: kvl(mxscls,6)
  integer, save :: nsc
  integer, save :: nks
  integer, save :: nnt
  data siv /mxscls*0/
  data nsi /mxscls*0/
  data nki /mxscls*0/
  data sfv /mxscls*0/
  data scy /mxscls*0/
  data ftv /4*0/
  data tvl /4*0/
  data kvl /mxsclsx*0/
  data nsc /0/
  data nks /0/
  data nnt /0/
end module com_tflxtor

module com_thmfr
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxb = 99
  public :: thfr
  real(lrk), save :: thfr(mxb)
  data thfr /mxb*0/
end module com_thmfr

module com_tman
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxm = 9
  public :: ntbr, tpc, tkk, tcc, tjj, sct
  integer, save :: ntbr
  real(lrk), save :: tpc(mxm)
  real(lrk), save :: tkk(mxm)
  real(lrk), save :: tcc(mxm)
  real(lrk), save :: tjj(mxm)
  real(lrk), save :: sct
  data ntbr /0/
  data tpc /mxm*0/
  data tkk /mxm*0/
  data tcc /mxm*0/
  data tjj /mxm*0/
  data sct /0/
end module com_tman

module com_tmat
  use rd_kinds, only: wp
  implicit none
  private
  integer, parameter :: mtg = 500
  integer, parameter :: mtx = mtg*mtg
  public :: tj, tk, tc, dm
  real(wp), save :: tj(mtg,mtg)
  real(wp), save :: tk(mtg,mtg)
  real(wp), save :: tc(mtg,mtg)
  integer, save :: dm
  data tj /mtx*0/
  data tk /mtx*0/
  data tc /mtx*0/
  data dm /0/
end module com_tmat

module com_tmdm
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mtg = 500
  integer, parameter :: mtx = mtg*mtg
  public :: tmd
  real(lrk), save :: tmd(mtg,mtg)
  data tmd /mtx*0/
end module com_tmdm

module com_tmdn
  implicit none
  private
  integer, parameter :: mxtmdn = 15
  public :: tmdnb, ntmdn
  integer, save :: tmdnb(mxtmdn)
  integer, save :: ntmdn
  data tmdnb /mxtmdn*0/
  data ntmdn /0/
end module com_tmdn

module com_tmsgs
  implicit none
  private
  integer, parameter :: mxg5 = 180
  public :: tmsg
  character(len=50), save :: tmsg(mxg5)
  data tmsg /'  Campbell Diagram','  Critical Speeds (rpm)','  Critical Frequencies (Hz)', &
    & '  Natural frequencies (rpm) x (Hz)','  Calculation range (rpm)','  Eigenvalues','  Logarithmic Decrement', &
    & '  speed(rd/s) eig-> ','  speed(rpm)   LD->','  Undamped Critical Speed Map', &
    & '  Angular Undamped Critical Speed Map','  with gyroscopic effect','  speed (rpm)', &
    & '  bearing radial stiffness (N/m)','  bea  kxx               kzz','  k      c. speed->', &
    & '  Unbalance Response - modes :','  point','  Shaft Extremity','  coordinate','  Automatic Response Analysis', &
    & '  amplif. low limit','  rpm','  max. disp. (m)','amplif. factor','point','status','(n)ormal','(F)ail', &
    & '(i)nital','(f)inal','mirror','  Amplitude (rpm) x (m)','  Phase (rpm) x (rad)', &
    & '  Critical speed (N/m) x (rpm)','  Mode Shape','  Frequency','  mode =','freq (Hz)','(Hz) dir =', &
    & '  Projected Displacement (m)','  y (m)','  Displacement Shape','  sec.','  speed =','  x (m)','  z (m)', &
    & '  Time Response - modes :','  Orbit points :','  plane','  Module Response - deg:','  module (m)', &
    & '  Elastic Line','  Horizontal angle =','  Acceleration of Gravity g (m/s^2):','  force(N)','  bearing', &
    & '  Displacements','  gx (rad)','  gz (rad)','  Bearing Reaction (N, Nm)','  x','  z',' Equivalent Stiffness', &
    & ' torque','  atan2(z,x) (rad)','  (x^2+z^2)^.5 (m)',' os user :',' input :',' calculation options :', &
    & ' Campbell diagram',' mode/speed shape',' unbalance response',' time response',' geometry export', &
    & ' with speed dep.bearing params',' static elastic line',' undamped critical speed map', &
    & ' with bearing support params',' export matrix HB',' export matrix MM',' HPGL plot output', &
    & ' undamped angular critical speed map',' speed dep. bearing parameters', ' calculation summary', &
    & ' number of sections = ', ' matrix size        = ', ' section mass  (kg) = ', ' disk mass     (kg) = ', &
    & ' concent. mass (kg) = ', ' rotor mass    (kg) = ', ' rotor length   (m) = ', ' center of mass (m) = ', &
    & ' ELAPSED (s):','  Graph Data','f =',' y = ',' dir =',' (rpm)',' - rpm:','  Relative Angular Displacement', &
    & ' static torque analysis','   division      Torque     ang.disp    yield str', &
    & '       m           Nm          rad         MPa',' Torsion Frequency Response - mode:', &
    & '  Amplitude (rad/s) x (rad)','  Phase (rad/s) x (rad)','  rad/s ',' Torsion Campbell Diagram', &
    & '   stress    sf  dir','        MPa     pu',' Torsion Periodic Steady-State Response', &
    & '  max. div. ang. disp. (rad)',' harmonic contents of angular displacement (rad)', &
    & ' order:frequency (rad/s):amplitude < angle (rad)',' Input Data Torque (Nm)','   time(s) y(m)->', &
    & ' Torsion Output Angle (rad)','   time(s) index->',' Torsion Time Transient Response', &
    & 'intial integ. time       (s):','final  integ. time       (s): ','integ. time step         (s):', &
    & 'integ. result step       (s):','ind. pos.(m) damp.(Nm/rad/s):',' Total Angular Displacement (rad)', &
    & '  max. div. torque      (Nm)',' Torsion Output Torque at Division (Nm)',' Torsion Mode Shape', &
    & ' Angular Displacement (rad/s) x (rad)',' Torsion Output Torque at division (rad/s) x (Nm)', &
    & ' Input Interpolated Torque (Nm)',' Angular Displacement at division (rad)', &
    & ' Angular Displacement at division (rad/s) x (rad)','max. stress (MPa)', &
    & ' Torsion Output Shear Stress at div.(rad/s) x (Pa)','  max. tot. ang. disp. (rad)', &
    & '  Bearing / Support Displacement (m)','   dist.','   conc.','  weight','  stiffness', &
    & 'numerical integration       :','   sum',' Bending moment at division (Nm)', &
    & '  Bearing / Support Stiffness (N/m)',' Shear Force constant on Element (N)',' Median filter width (1=no):', &
    & ' min / max',' bea speed (rpm)       kxx               kzz','  Maximum Values','  rated speed (rpm)', &
    & '  Bearing Parameters',' Flexural-Torsion Analysis',' section index :',' notch',' keyseat',' step', &
    & ' stress (Pa)','       tqmx         tqal         tqav         bend','   fat.fact   result(Pa)', &
    & ' stress concentration factors','      crack      torsion         bend        axial', &
    & ' Von-Mises equivalent stress (Pa)','        max          alt          avg',' fatigue safety factors', &
    & '     static      Goodman         ASME',' kind : ',' main dimensions (m)', &
    & '      outer         step       radius',' add.factor   tor.factor   bnd.factor','at right','at left', &
    & ' bending stress',' supp = ',' export matrix plain',' ',' ',' ',' '/
end module com_tmsgs

module com_tor
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxm = 9
  public :: kph, kth
  real(lrk), save :: kph(mxm)
  real(lrk), save :: kth(mxm)
  data kph /mxm*0/
  data kth /mxm*0/
end module com_tor

module com_touopt
  implicit none
  private
  public :: telm, tlopt
  integer, save :: telm
  logical, save :: tlopt(2)
  data telm /2/
  data tlopt /.false.,.false./
end module com_touopt

module com_tpfrt
  use rd_kinds, only: lrk
  implicit none
  private
  public :: fprt, fprts
  real(lrk), save :: fprt
  real(lrk), save :: fprts
  data fprt /0/
  data fprts /0/
end module com_tpfrt

module com_trncli
  implicit none
  private
  public :: trn_cli
  logical, save :: trn_cli
  data trn_cli /.false./
end module com_trncli

module com_trnctl
  implicit none
  private
  public :: trn_enabled, trn_gravity, trn_unbalance, trn_convergence, trn_model, trn_speed_kind, trn_init_kind, &
    & trn_stride, trn_nprof, trn_nic, trn_nforce, trn_out_policy, trn_monitor_dof, trn_analysis_mode
  logical, save :: trn_enabled
  logical, save :: trn_gravity
  logical, save :: trn_unbalance
  logical, save :: trn_convergence
  integer, save :: trn_model
  integer, save :: trn_speed_kind
  integer, save :: trn_init_kind
  integer, save :: trn_stride
  integer, save :: trn_nprof
  integer, save :: trn_nic
  integer, save :: trn_nforce
  integer, save :: trn_out_policy
  integer, save :: trn_monitor_dof
  integer, save :: trn_analysis_mode
end module com_trnctl

module com_trnforce
  use rd_kinds, only: wp
  implicit none
  private
  integer, parameter :: trn_mforce = 20
  integer, parameter :: trn_mfpt = 999
  public :: trn_fdof, trn_fnpt, trn_ftime, trn_fvalue
  integer, save :: trn_fdof(trn_mforce)
  integer, save :: trn_fnpt(trn_mforce)
  real(wp), save :: trn_ftime(trn_mforce,trn_mfpt)
  real(wp), save :: trn_fvalue(trn_mforce,trn_mfpt)
end module com_trnforce

module com_trnic
  use rd_kinds, only: wp
  implicit none
  private
  integer, parameter :: trn_mic = 500
  public :: trn_icdof, trn_icq, trn_icv
  integer, save :: trn_icdof(trn_mic)
  real(wp), save :: trn_icq(trn_mic)
  real(wp), save :: trn_icv(trn_mic)
end module com_trnic

module com_trnprof
  use rd_kinds, only: wp
  implicit none
  private
  integer, parameter :: trn_mprof = 999
  public :: trn_ptime, trn_prpm, trn_pphase
  real(wp), save :: trn_ptime(trn_mprof)
  real(wp), save :: trn_prpm(trn_mprof)
  real(wp), save :: trn_pphase(trn_mprof)
end module com_trnprof

module com_trnreadbuf
  implicit none
  private
  public :: trn_pending, trn_pending_line
  logical, save :: trn_pending
  character(len=512), save :: trn_pending_line
end module com_trnreadbuf

module com_trntime
  use rd_kinds, only: wp
  implicit none
  private
  public :: trn_tstart, trn_tend, trn_dt, trn_beta, trn_gamma, trn_phase0, trn_audit_hz
  real(wp), save :: trn_tstart
  real(wp), save :: trn_tend
  real(wp), save :: trn_dt
  real(wp), save :: trn_beta
  real(wp), save :: trn_gamma
  real(wp), save :: trn_phase0
  real(wp), save :: trn_audit_hz
end module com_trntime

module com_tshyi
  use rd_kinds, only: lrk
  implicit none
  private
  public :: tshyipu
  real(lrk), save :: tshyipu
  data tshyipu /0.3_lrk/
end module com_tshyi

module com_tstest
  implicit none
  private
  integer, parameter :: mxtstf = 5
  integer, parameter :: mxtstft = mxtstf*2
  public :: eqstid, ntest
  integer, save :: eqstid(mxtstf,2)
  integer, save :: ntest
  data ntest /0/
  data eqstid /mxtstft*0/
end module com_tstest

module com_ttraneq
  implicit none
  private
  integer, parameter :: mxttra = 5
  public :: tequt
  character(len=255), save :: tequt(mxttra)
end module com_ttraneq

module com_ttransc
  use rd_kinds, only: lrk
  implicit none
  private
  public :: ttris, ttrrs, ttrit, ttret
  real(lrk), save :: ttris
  real(lrk), save :: ttrrs
  real(lrk), save :: ttrit
  real(lrk), save :: ttret
  data ttris /0/
  data ttrrs /0/
  data ttrit /0/
  data ttret /0/
end module com_ttransc

module com_ttransd
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxttra = 5
  integer, parameter :: mxttrd = 10000
  integer, parameter :: mxttrtot = mxttra*mxttrd
  public :: ttrmd, ttrdtt, ttrdta, nttra, ttrdsz, iseqt
  real(lrk), save :: ttrmd(mxttra)
  real(lrk), save :: ttrdtt(mxttrd)
  real(lrk), save :: ttrdta(mxttra,mxttrd)
  integer, save :: nttra
  integer, save :: ttrdsz
  logical, save :: iseqt
  data ttrmd /mxttra*0/
  data ttrdtt /mxttrd*0/
  data ttrdta /mxttrtot*0/
  data nttra /0/
  data ttrdsz /0/
  data iseqt /.false./
end module com_ttransd

module com_unb
  use rd_kinds, only: lrk
  implicit none
  private
  public :: nini_r, nfin_r, dw_r
  real(lrk), save :: nini_r
  real(lrk), save :: nfin_r
  real(lrk), save :: dw_r
  data nini_r /0/
  data nfin_r /0/
  data dw_r /0/
end module com_unb

module com_unb0
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxr = 9
  public :: pr, desp, ori, np, nm
  real(lrk), save :: pr(mxr)
  real(lrk), save :: desp(mxr)
  real(lrk), save :: ori(mxr)
  integer, save :: np
  integer, save :: nm
  data pr /mxr*0/
  data desp /mxr*0/
  data ori /mxr*0/
  data np /0/
  data nm /0/
end module com_unb0

module com_unb1
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxb = 99
  public :: ndd, mu, ed, tpf, nb
  real(lrk), save :: ndd(mxb)
  real(lrk), save :: mu(mxb)
  real(lrk), save :: ed(mxb)
  integer, save :: tpf(mxb)
  integer, save :: nb
  data ndd /mxb*0/
  data mu /mxb*0/
  data ed /mxb*0/
  data tpf /mxb*0/
  data nb /0/
end module com_unb1

module com_view
  use rd_kinds, only: lrk
  implicit none
  private
  public :: vv
  real(lrk), save :: vv(4,4)
end module com_view

module com_vldo
  implicit none
  private
  integer, parameter :: jvop = 20
  public :: vopt
  character(len=1), save :: vopt(jvop)
  data vopt /'c','m','f','t','$','e','$','s','k','b','$','x','$','p','a','j','$','$','n','r'/
end module com_vldo

module com_wmsgs
  implicit none
  private
  integer, parameter :: mxg2 = 45
  public :: wmsg
  character(len=50), save :: wmsg(mxg2)
  data wmsg /'guess legacy input file','truncated output','delta x=0 ','speed increment<=0','speed limits', &
    & 'on unb. position','on resp. position','no/invalid support','of bear.param kind',' ','invalid speed', &
    & 'stiffness range','of file kind','of file name','divisions number','sections number','orbit','excitation', &
    & 'disk','response','on standard io','folder name','file name','no argument','invalid mode', &
    & 'invalid number of modes','linear extrapolation','no or low excitation','invalid coup. inertia', &
    & 't. damping too low, added min damping','time response amplitude','number read','value out of expected range', &
    & ' crack factor',' surface factor',' sizing factor',' reliability factor',' step change t/r',' notch h/r', &
    & ' keyseat proximity dimension<0',' keyseat "B" r/d',':torsion only','speed extrap.beyond upper/lower limit', &
    & ' WARNING!',' '/
end module com_wmsgs

module com_world
  use rd_kinds, only: lrk
  implicit none
  private
  public :: ww
  real(lrk), save :: ww(4,4)
end module com_world

module com_ws
  implicit none
  private
  public :: c, w
  logical, save :: c
  logical, save :: w
end module com_ws

module com_ymc
  use rd_kinds, only: lrk
  implicit none
  private
  integer, parameter :: mxm = 9
  public :: nbrg, rks, pc
  integer, save :: nbrg
  real(lrk), save :: rks
  real(lrk), save :: pc(mxm)
  data nbrg /0/
  data rks /0/
  data pc /mxm*0/
end module com_ymc

module com_yscl
  use rd_kinds, only: lrk
  implicit none
  private
  public :: scxmn, scxmx, scymn, scymx
  real(lrk), save :: scxmn
  real(lrk), save :: scxmx
  real(lrk), save :: scymn
  real(lrk), save :: scymx
  data scxmn /0/
  data scxmx /0/
  data scymn /0/
  data scymx /0/
end module com_yscl
