!> @file rd_textfun.f90
!> @brief Text/message functions returning CHARACTER results.
!>
!> These were assumed-length CHARACTER(*) functions (obsolescent).  The
!> result length is now an explicit first argument (lres_), with each
!> caller passing the length it historically declared, so the returned
!> text is unchanged.  Generated by tools/pass_std.py.
module rd_textfun
  implicit none
  private
  public :: cadjf, ciff, cpinfof, errmsgf, famsgf, femsgf, fhmsgf, fmmsgf, fmtmsgf, fomsgf, fopmsf, fwmsgf, hlpmsgf, &
    & mexmsgf, msgf, msizef, pgycscidf, pinfo, pltmsgf, rvinfof, scmsgf, sinfo, sjoinif, sjoinrf, tpeqstidf, txtmsgf, &
    & warnmsgf, xtime

contains

  function cadjf(lres_, cin,isz)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: cadjf
  !
    integer :: isz
    character(len=*) :: cin
  !
    character(len=1) :: blank
    parameter (blank = ' ')
    integer :: i, k, irs
  !
    intrinsic :: len, min
  !
  !     initialize return and reject empty/non-positive requests
    cadjf = blank
    if (len(cin) .gt. 0 .and. isz .gt. 0) then
  !       find the first non-blank character using input length as bound.
  !       This handles right-justified one-character flags such as
  !       '         D' without producing an invalid reversed substring.
      i = 1
      do while(i .le. len(cin))
        if (cin(i:i) .gt. blank) exit
        i = i+1
      end do
  !
      if (i .le. len(cin)) then
  !         copy no more than requested, available input, or return capaci
        k = len(cadjf)
        irs = min(isz,k,len(cin)-i+1)
        if (irs .gt. 0) cadjf(1:irs) = cin(i:i+irs-1)
      end if
    end if
  !
    return
  !
  end function cadjf

  function ciff(lres_, lcn,ctr,cfl)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: ciff
  !
    logical :: lcn
    character(len=*) :: ctr, cfl
  !
    if (lcn) then
      ciff = ctr
    else
      ciff = cfl
    end if
  !
    return
  !
  end function ciff

  function cpinfof(lres_, csiz)
    use, intrinsic :: iso_fortran_env, only: compiler_version
  !     used inside include
    use iso_fortran_env, only: compiler_version
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: cpinfof
  !
    integer :: csiz
  !
  !     compiler info
  !     $Id$
  !
  !>    @file compiler.inc
  !
  !> \verbatim
  !>    compiler info. windows (default) / linux
  !>    could be generated on makefile.
  !>    only declarations here.
  !> \endverbatim
  !
    character(len=256) :: comp
    dimension comp(2)
  !      parameter (comp = (/
  !     &  'GNU Fortran (GCC) 4.6.2                            '
  !     & ,'gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC)'
  !     & /) )
    parameter (comp = (/&
    &compiler_version()&
    &,compiler_version()&
    &/) )

  !
  !
    intrinsic :: len_trim
  !
  !     preprocessor
  !
  !     fpp cpp
#ifdef _LINUX
    cpinfof = comp(2)
#else
  !     windows
    cpinfof = comp(1)
#endif
    csiz = len_trim(cpinfof)
  !
    return
  !
  end function cpinfof

  function errmsgf(lres_, imsg)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: errmsgf
  !
    integer :: imsg
  !
  !
    errmsgf = msgf(50, imsg,1)
  !
    return
  !
  end function errmsgf

  function famsgf(lres_, mname,nmsg,opttxt,usesep,ikd)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: famsgf
  !
    character(len=*) :: mname, opttxt
    integer :: nmsg, usesep, ikd
  !
    integer :: i, j, k
    character(len=1) :: blank
    character(len=99) :: buf
    dimension buf(3)
    parameter(blank = ' ')
  !
    intrinsic :: len, len_trim, min
  !
    famsgf = blank
    do i = 1,3
      buf(i) = blank
    end do
    if (nmsg .gt. 0) then
  !       kind
      if (ikd .eq. 0) then
  !         0=error
        buf(1) = errmsgf(99, nmsg)
      else if (ikd .eq. 1) then
  !         1=warning
        buf(1) = warnmsgf(99, nmsg)
      else if (ikd .eq. 2) then
  !         2=help
        buf(1) = hlpmsgf(99, nmsg)
      else if (ikd .eq. 3) then
  !         3=matrix export
        buf(1) = mexmsgf(99, nmsg)
      end if
    end if
    i = len_trim(buf(1))
    if (i .gt. 0) then
      j = len_trim(opttxt)
      if (j .gt. 0) then
        buf(3) = fmtmsgf(99, mname,buf(1),opttxt,usesep)
      else
        buf(3) = fmtmsgf(99, mname,buf(1),blank,usesep)
      end if
    end if
    i = len(famsgf)
    j = len(buf(3))
    k = min(i,j)
    if (k .gt. 0) famsgf = buf(3)(1:k)
  !
    return
  !
  end function famsgf

  function femsgf(lres_, mname,nemsg,nwmsg,usesep)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: femsgf
  !
    character(len=*) :: mname
    integer :: nemsg, nwmsg, usesep
  !
    integer :: i, j, k
    character(len=1) :: blank
    character(len=99) :: buf
    dimension buf(3)
    parameter(blank = ' ')
  !
    intrinsic :: len, min
  !
    do i = 1,3
      buf(i) = blank
    end do
    if (nemsg .gt. 0) then
      buf(1) = errmsgf(99, nemsg)
    end if
    i = len_trim(buf(1))
    if (i .gt. 0) then
      if (nwmsg .gt. 0) then
        buf(2) = warnmsgf(99, nwmsg)
        buf(3) = fmtmsgf(99, mname,buf(1),buf(2),usesep)
      else
        buf(3) = fmtmsgf(99, mname,buf(1),blank,usesep)
      end if
    end if
    i = len(femsgf)
    j = len(buf(3))
    k = min(i,j)
    femsgf = buf(3)(1:k)
  !
    return
  !
  end function femsgf

  function fhmsgf(lres_, mname,nhmsg,opttxt,usesep)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: fhmsgf
  !
    character(len=*) :: mname, opttxt
    integer :: nhmsg, usesep
  !
    integer :: i, j, k
    character(len=1) :: dl
    character(len=99) :: cbf
    parameter (dl = '$')
    intrinsic :: len, len_trim, min
  !
  !     get help message to buffer -> cbf
    cbf = famsgf(99, mname,nhmsg,opttxt,usesep,2)
    i = len_trim(cbf)
    j = len(fhmsgf)
    k = min(i+1,j)
    fhmsgf = dl//cbf(1:k)
  !
    return
  !
  end function fhmsgf

  function fmmsgf(lres_, mname,nmmsg,opttxt,usesep)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: fmmsgf
  !
    character(len=*) :: mname, opttxt
    integer :: nmmsg, usesep
  !
  !
    fmmsgf = famsgf(99, mname,nmmsg,opttxt,usesep,3)
  !
    return
  !
  end function fmmsgf

  function fmtmsgf(lres_, mname,msgtxt,opttxt,usesep)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: fmtmsgf
  !
    integer :: usesep
    character(len=*) :: mname, msgtxt, opttxt
  !
    character(len=128) :: buf
    character(len=6) :: nomsg
    character(len=2) :: poi
    character(len=1) :: blank, sep
    dimension sep(2)
    parameter (poi = '->',blank = ' ',&
    &sep = (/'<','>'/),nomsg = 'no msg')
    integer :: ib, in, i1, ip, i2, i3, it
  !
    intrinsic :: len, len_trim, min
  !
    buf = blank
    fmtmsgf = blank
  !     lengths
  !     module name
    i1 = len_trim(mname)
  !     message text
    i2 = len_trim(msgtxt)
  !     optional text
    i3 = len_trim(opttxt)
  !     module name pointer length
    ip = len_trim(poi)
  !     no message length
    in = len_trim(nomsg)
  !     buffer length
    ib = len(buf)
  !
  !     has module name
    if (i1 .gt. 0) then
  !       message is not blank
      if (i2 .gt. 0) then
  !         total length
        it = min(i1+ip+i2+1,ib)
        write(buf(1:it),20) mname(1:i1),poi(1:ip),msgtxt(1:i2)
  !       message is blank
      else
        it = min(i1+ip+in+1,ib)
        write(buf(1:it),20) mname(1:i1),poi(1:ip),nomsg(1:in)
      end if
  !     module name is blank
    else
  !       message is not blank
      if (i2 .gt. 0) then
        it = i2
        write(buf(1:it),10) msgtxt(1:i2)
  !       message is blank
      else
        it = in
        write(buf(1:it),10) nomsg(1:it)
      end if
    end if
  !     optional text
    if (i3 .gt. 0) then
      it = it+1
  !       check for left space in buffer
      if (it .lt. ib) then
  !         optional text with separators
  !         may have truncation
        if (usesep .ne. 0) then
          i1 = min(ib-2,i3)
          write(buf(it:),20) sep(1),opttxt(1:i1),sep(2)
        else
          i1 = min(ib,i3)
          write(buf(it:),10) opttxt(1:i1)
        end if
      end if
    end if
  !     total buffer length
    it = len_trim(buf)
  !     function return defined length
    in = len(fmtmsgf)
  !     check max return length
    i1 = min(in,it)
    if (i1 .gt. 0) fmtmsgf = buf(1:i1)
  !
    return
  !
  10 format(a)
  20 format(3a)
  !
  end function fmtmsgf

  function fomsgf(lres_, mname,nemsg,opttxt,usesep)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: fomsgf
  !
    character(len=*) :: mname, opttxt
    integer :: nemsg, usesep
  !
  !
    fomsgf = famsgf(99, mname,nemsg,opttxt,usesep,0)
  !
    return
  !
  end function fomsgf

  function fopmsf(lres_, mname,nemsg,pname,fname)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: fopmsf
  !
    character(len=*) :: mname, pname, fname
    integer :: nemsg
  !
    integer :: i, j, k
    character(len=1) :: blank, ccm
    character(len=65) :: msg
    character(len=99) :: buf
    dimension ccm(2)
    parameter(blank = ' ',ccm = (/'(',')'/))
  !
    intrinsic :: len, len_trim, min
  !
    msg = blank
    buf = blank
    if (nemsg .gt. 0) then
      buf = errmsgf(99, nemsg)
    end if
  !     error message
    j = len_trim(buf)
  !     file name
    i = len_trim(fname)
  !     section name
    k = len_trim(pname)
  !     check message parts
    if (j .gt. 0 .and. k .gt. 0) then
  !       composed error message
      write(msg,5)buf(1:j),ccm(1),pname(1:k),ccm(2)
    else if (j .gt. 0) then
      write(msg,15)buf(1:j)
    end if
  !
    if (i .gt. 0) then
      fopmsf = fmtmsgf(99, mname,msg,fname(1:i),1)
    else
      fopmsf = fmtmsgf(99, mname,msg,blank,1)
    end if
  !
    return
  !
  5 format(4a)
  15 format(a)
  !
  end function fopmsf

  function fwmsgf(lres_, mname,nwmsg,opttxt,usesep)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: fwmsgf
  !
    character(len=*) :: mname, opttxt
    integer :: nwmsg, usesep
  !
  !
    fwmsgf = famsgf(99, mname,nwmsg,opttxt,usesep,1)
  !
    return
  !
  end function fwmsgf

  function hlpmsgf(lres_, imsg)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: hlpmsgf
  !
    integer :: imsg
  !
  !
    hlpmsgf = msgf(50, imsg,4)
  !
    return
  !
  end function hlpmsgf

  function mexmsgf(lres_, imsg)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: mexmsgf
  !
    integer :: imsg
  !
  !
    mexmsgf = msgf(50, imsg,0)
  !
    return
  !
  end function mexmsgf

  function msgf(lres_, imsg,ikd)
    use com_emsgs, only: emsg
    use com_hmsgs, only: hmsg
    use com_mmmsg, only: exmsg
    use com_pmsgs, only: pmsg
    use com_scmsg, only: lmc
    use com_tmsgs, only: tmsg
    use com_wmsgs, only: wmsg
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: msgf
  !
    integer :: imsg, ikd
  !
  !     matrix export error messages
    integer :: mxg0
    parameter (mxg0 = 15)
  !     error messages
    integer :: mxg1
    parameter (mxg1 = 35)
  !     warning messages
    integer :: mxg2
    parameter (mxg2 = 45)
  !     plot messages
    integer :: mxg3
    parameter (mxg3 = 70)
  !     help messages
    integer :: mxg4
    parameter (mxg4 = 30)
  !     output text messages
    integer :: mxg5
    parameter (mxg5 = 180)
  !     screen messages
    integer :: nsmsg
    parameter(nsmsg = 30)
  !
    integer :: i, j, k
    character(len=1) :: blank
    character(len=13) :: civ
    character(len=50) :: cms
    parameter (blank =' ',civ = 'invalid index')
  !
    intrinsic :: len, len_trim, min
  !
  !     init invalid
    msgf = blank
    cms = civ
    if (ikd .eq. 0) then
  !       matrix export error messages
      if (imsg .gt. 0 .and. imsg .le. mxg0) then
        cms = exmsg(imsg)
      end if
    else if (ikd .eq. 1) then
  !       error messages
      if (imsg .gt. 0 .and. imsg .le. mxg1) then
        cms = emsg(imsg)
      end if
    else if (ikd .eq. 2) then
  !       warning messages
      if (imsg .gt. 0 .and. imsg .le. mxg2) then
        cms = wmsg(imsg)
      end if
    else if (ikd .eq. 3) then
  !       plot messages
      if (imsg .gt. 0 .and. imsg .le. mxg3) then
        cms = pmsg(imsg)
      end if
    else if (ikd .eq. 4) then
  !       help messages
      if (imsg .gt. 0 .and. imsg .le. mxg4) then
        cms = hmsg(imsg)
      end if
    else if (ikd .eq. 5) then
  !       output text messages
      if (imsg .gt. 0 .and. imsg .le. mxg5) then
        cms = tmsg(imsg)
      end if
    else if (ikd .eq. 6) then
  !       screen messages
      if (imsg .gt. 0 .and. imsg .le. nsmsg) then
        cms = lmc(imsg)
      end if
    end if
  !     message size
    i = len_trim(cms)
  !     return size
    j = len(msgf)
  !     minimum
    k = min(i,j)
  !     return
    if (k .gt. 0) msgf = cms(1:k)
  !
    return
  !
  end function msgf

  function msizef(lres_, pdm,lop)
    use com_scmsg1, only: msz
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: msizef
  !
    integer :: pdm
    logical :: lop
  !
    integer :: iz
    character(len=1) :: blank, cx, cb, co
    character(len=99) :: msg
    parameter (blank = ' ',cx = 'x',cb = 'b')
  !
  !     screen message, see messages.f
  !
    intrinsic :: len, min
  !
    msizef = blank
    co = ciff(1, lop,cb,blank)
    write(msg,5) msz,pdm,cx,pdm,co
    iz = min(len(msizef),99)
    if (iz .gt. 0) msizef = msg(1:iz)
  !
    return
  !
  5 format(a,i4,a,i4,a)
  !
  end function msizef

  function pgycscidf(lres_)
    use com_gycsedc, only: gycsedid, gycsedvl, ngycsed
    use rd_kinds, only: lrk
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: pgycscidf
  !
    integer :: mxgc
    parameter (mxgc = 5)
  !
    integer :: ii, jj, kk, ll
    character(len=1) :: bl, cm, cz, ds
    character(len=2) :: c2
    character(len=8) :: c8
    character(len=60) :: buf
  !
    parameter (bl = ' ',cm = ',',cz = '0',ds = '-')
    data buf/bl/
  !
    intrinsic :: len, len_trim, min
  !
    pgycscidf = bl
    do ii = 1,ngycsed
  !       id
      if (gycsedid(ii) .lt. 10) then
        write(c2,5) gycsedid(ii)
      else if (gycsedid(ii) .lt. 100) then
        write(c2,15) gycsedid(ii)
      else
  !         errror, not supposed to be

      end if
      jj = len_trim(c2)
  !       value
      write(c8,25) gycsedvl(ii)
  !       remove right zeros
      do ll = len(c8),1,-1
        if (c8(ll:ll) .ne. cz) exit
      end do
  !
      kk = len_trim(buf)
      if (ii .lt. ngycsed) then
        write(buf(kk+1:),35) c2(1:jj),ds,c8(1:ll),cm
      else
  !         last, no comma
        write(buf(kk+1:),45) c2(1:jj),ds,c8(1:ll)
      end if
  !
    end do
  !
    kk = len_trim(buf)
    ll = len(pgycscidf)
    jj = min(kk,ll)
    if (jj .gt. 0) pgycscidf = buf(1:jj)
  !
    return
  !
  5 format(i1)
  15 format(i2)
  25 format(f8.6)
  35 format(4a)
  45 format(3a)
  !
  end function pgycscidf

  function pinfo(lres_, lgn)
    use com_inf, only: vrs, dta, rgh, sid
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: pinfo
  !
    logical :: lgn
  !
  !     system identification
  !
    integer :: i
    character(len=1) :: dl
    character(len=5) :: cvr
    parameter (dl = '$',cvr = ' - p:')
    character(len=50) :: buf
  !
    intrinsic :: len_trim, min
  !
    i = len_trim(rgh)
  !     check for log info
    if (lgn) then
  !       log info -> dl
  !       company name and production year
      write(buf,10) dl,rgh(1:i),cvr,dta
    else
      write(buf,20) rgh(1:i),cvr,dta
    end if
  !     return size
    i = min(len(pinfo),len_trim(buf))
    pinfo = buf(1:i)
    return
  !
  10 format(4a)
  20 format(3a)
    !
  end function pinfo

  function pltmsgf(lres_, imsg)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: pltmsgf
  !
    integer :: imsg
  !
  !
    pltmsgf = msgf(50, imsg,3)
  !
    return
  !
  end function pltmsgf

  function rvinfof(lres_, csiz)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: rvinfof
  !
    integer :: csiz
  !
  !     =================================================================
  !     $Id$
  !
  !>    @file revision.inc
  !
  !> \verbatim
  !>     revision control, intended to track i/o changes.
  !>     only declarations here.
  !> \endverbatim
  !
    character(len=5) :: rev
  !     parameter (rev = '2.0.0')
    parameter (rev = '2.1.0')
  !
    intrinsic :: len_trim
  !
    rvinfof = rev
  !
    csiz = len_trim(rvinfof)
  !
    return
  !
  end function rvinfof

  function scmsgf(lres_, imsg)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: scmsgf
  !
    integer :: imsg
  !
  !
    scmsgf = msgf(50, imsg,6)
  !
    return
  !
  end function scmsgf

  function sinfo(lres_, lgn,ifl)
    use com_inf, only: vrs, dta, rgh, sid
    use com_nmi, only: inm, sbv
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: sinfo
  !
    logical :: lgn
    integer :: ifl
  !
  !     internal name
  !
  !     system identification
  !
    integer :: i, j, iiff
    character(len=1) :: dl, blank
    character(len=3) :: vr, rv
    character(len=50) :: buf
    parameter (dl = '$',blank = ' ',vr = '-v:',rv = ' r:')
  !
    intrinsic :: len, len_trim, min
  !
    i = iiff(ifl .ne. 0,len_trim(sid),len_trim(inm))
  !     check for log info
    if (lgn) then
  !       log info -> dl
      if (ifl .ne. 0) then
  !         full application name, version, sub-version, revision
        write(buf,10) dl,sid(1:i),vr,vrs,sbv,rv,rvinfof(5, j)
      else
  !         short application name, version, sub-version, revision
        write(buf,10) dl,blank//inm(1:i),vr,vrs,sbv,rv,rvinfof(5, j)
      end if
    else
      if (ifl .ne. 0) then
  !         full application name, version, sub-version, revision
        write(buf,20) sid(1:i),vr,vrs,sbv,rv,rvinfof(5, j)
      else
  !         short application name, version, sub-version, revision
        write(buf,20) blank//inm(1:i),vr,vrs,sbv,rv,rvinfof(5, j)
      end if
    end if
  !     return size
    i = min(len(sinfo),len_trim(buf))
    sinfo = buf(1:i)
  !
    return
  !
  10 format(7a)
  20 format(6a)
  !
  end function sinfo

  function sjoinif(lres_, iin,sfm,nin,ndm)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: sjoinif
  !
    integer :: iin, nin, ndm
    dimension iin(ndm)
    character(len=*) :: sfm
  !
    integer :: ii, io, jj, kk, ll, mm, nn
    character(len=1) :: c1
    character(len=7) :: nmm
    character(len=20) :: sdm
    dimension c1(2)
    parameter (c1 = (/' ',','/),nmm = 'sjoinif')
  !
    intrinsic :: len, len_trim
  !
    nn = 1
  !     buffer size
    mm = len(sdm)
  !     output size
    ll = len(sjoinif)
  !     init output with a blank
    sjoinif = c1(1)
  !     loop over input elements
    do ii = 1,nin
      kk = len_trim(sfm)
      if (kk .gt. 0) then
  !         write each element to a buffer using given format
        write(sdm,sfm(1:kk),err=10,iostat=io) iin(ii)
      else
        write(sdm,*,err=10,iostat=io) iin(ii)
      end if
  !       useful output buffer size
      jj = len_trim(sdm)
  !       search first non blank
      do kk = 1,jj
        nn = kk
        if (sdm(kk:kk) .gt. c1(1)) exit
      end do
  !       add comma if not last element and have size
      if (ii .lt. nin .and. jj .lt. mm) then
        sdm = sdm(nn:jj)//c1(2)
      else
        sdm = sdm(nn:jj)
      end if
      jj = len_trim(sdm)
  !       output size
      kk = len_trim(sjoinif)
      if (kk+jj .lt. ll) then
  !         have room to output
        sjoinif = sjoinif(1:kk)//sdm(1:jj+1)
      else
  !         no room left warning
        call elmsgw(0,2,nmm)
        exit
      end if
  !       write warning
  10  if (io .ne. 0) call elmsgw(0,32,nmm)
    end do
  !
    return
  !
  end function sjoinif

  function sjoinrf(lres_, rin,sfm,nin,ndm)
    use rd_kinds, only: lrk
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: sjoinrf
  !
    integer :: nin, ndm
    real(lrk) :: rin
    dimension rin(ndm)
    character(len=*) :: sfm
  !
    integer :: ii, io, jj, kk, ll, mm, nn, oo
    character(len=1) :: c1
    character(len=7) :: nmm
    character(len=20) :: sdm
    logical :: hcm
    dimension c1(4)
    parameter (c1 = (/' ',',','.','0'/),nmm = 'sjoinrf')
  !
    intrinsic :: index, len, len_trim
  !
  !     buffer size
    mm = len(sdm)
  !     output size
    ll = len(sjoinrf)
  !     init output with a blank
    sjoinrf = c1(1)
  !     loop over input elements
    do ii = 1,nin
      kk = len_trim(sfm)
  !       write each element to a buffer using given format
      if (kk .gt. 0) then
        write(sdm,sfm(1:kk),err=10,iostat=io) rin(ii)
      else
        write(sdm,*,err=10,iostat=io) rin(ii)
      end if
  !       useful output buffer size
      jj = len_trim(sdm)
  !       search first non blank
      do kk = 1,jj
        nn = kk
        if (sdm(kk:kk) .gt. c1(1)) exit
      end do
  !       add comma if not last element and have size
      if (ii .lt. nin .and. jj .lt. mm) then
        sdm = sdm(nn:jj)//c1(2)
      else
        sdm = sdm(nn:jj)
      end if
      jj = len_trim(sdm)
  !       has dot? check for at right zeros
      oo = index(sdm,c1(3))
      if (oo .gt. 0) then
  !         check for last comma
        hcm = sdm(jj:jj) .eq. c1(2)
  !         remove last comma from size
        if (hcm) jj = jj-1
  !         loop non significant zeros (at right)
        do kk = jj,oo+1,-1
          nn = kk
          if (sdm(kk:kk) .ne. c1(4)) exit
        end do
  !         remove non significant zeros (at right)
        sdm = sdm(1:nn)
  !         add coma again
        if (hcm) sdm = sdm(1:nn)//c1(2)
        jj = len_trim(sdm)
      end if
  !       output size
      kk = len_trim(sjoinrf)
      if (kk+jj .lt. ll) then
  !         have room to output
        sjoinrf = sjoinrf(1:kk)//sdm(1:jj+1)
      else
  !         no room left warning
        call elmsgw(0,2,nmm)
        exit
      end if
  !       write warning
  10  if (io .ne. 0) call elmsgw(0,32,nmm)
    end do
  !
    return
  !
  end function sjoinrf

  function tpeqstidf(lres_)
    use com_tstest, only: eqstid, ntest
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: tpeqstidf
  !
  !     equivalent stiffness for static
    integer :: mxtstf
    parameter (mxtstf = 5)
  !
    integer :: ii, jj, kk
    character(len=1) :: ccm
    character(len=5) :: bf1
    character(len=30) :: bf2
    dimension ccm(2)
    parameter (ccm = (/',','-'/))
  !
    intrinsic :: len, len_trim, min
  !
  !     output buffer
    bf2 = ' '
  !     loop on pairs
    do ii = 1,ntest
  !       check format for two indices
      if (eqstid(ii,1) .lt. 10 .and. eqstid(ii,2) .lt. 10) then
  !         both bellow 10
        write(bf1,5)eqstid(ii,1),ccm(2),eqstid(ii,2)
      else if (eqstid(ii,1) .lt. 10 .and. eqstid(ii,2) .gt. 9) then
  !         one bellow 10 other above 9
        write(bf1,15)eqstid(ii,1),ccm(2),eqstid(ii,2)
      else if (eqstid(ii,1) .gt. 9 .and. eqstid(ii,2) .lt. 10) then
  !         one bellow 10 other above 9
        write(bf1,25)eqstid(ii,1),ccm(2),eqstid(ii,2)
      else
  !         two above 9
        write(bf1,35)eqstid(ii,1),ccm(2),eqstid(ii,1)
      end if
  !       size of two intgers buffer
      kk = len_trim(bf1)
  !       size of output buffer
      jj = len_trim(bf2)
  !       coma just after first pair
      if(ii .eq. 1) then
        write(bf2(jj+1:),45)bf1(1:kk)
      else
        write(bf2(jj+1:),55)ccm(1),bf1(1:kk)
      end if
    end do
  !     function output size
    jj = len(tpeqstidf)
  !     output buffer size
    kk = len_trim(bf2)
  !     select minumum size
    ii = min(jj,kk)
  !     state output size
    tpeqstidf = bf2(1:ii)
  !
    return
  !
  5 format(i1,a,i1)
  15 format(i1,a,i2)
  25 format(i2,a,i1)
  35 format(i2,a,i2)
  45 format(a)
  55 format(2a)
  !
  end function tpeqstidf

  function txtmsgf(lres_, imsg)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: txtmsgf
  !
    integer :: imsg
  !
  !
    txtmsgf = msgf(50, imsg,5)
  !
    return
  !
  end function txtmsgf

  function warnmsgf(lres_, imsg)
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: warnmsgf
  !
    integer :: imsg
  !
    integer :: i, wid
    character(len=50) :: buf
    dimension buf(2)
  !     'WARNING!' !44
    parameter (wid = 44)
  !
    intrinsic :: abs, len_trim
  !
    buf(2) = msgf(50, abs(imsg),2)
    if (.not. imsg .lt. 0) then
      warnmsgf = buf(2)
    else
  !       WARNING
      buf(1) = msgf(50, wid,2)
      i = len_trim(buf(1))
      warnmsgf = buf(1)(1:i)//buf(2)
    end if
  !
    return
  !
  end function warnmsgf

  function xtime(lres_)
    use rd_kinds, only: lrk
    implicit none
    integer, intent(in) :: lres_
    character(len=lres_) :: xtime
  !
    integer :: lf
    character(len=1) :: blank
    character(len=3) :: cfm
    character(len=20) :: fmt, stime
    dimension cfm(2)
    parameter (blank = ' ',cfm = (/' (f','.2)'/))
    real(lrk) :: time
    real(lrk) :: values(2)
    data time/0/,values/2*0/
  !
  !     intrinsic functions
    intrinsic :: int, log10, min, len, len_trim

  !     intrinsic etime elapsed time
    call cpu_time(time)
  !     how much digits
    if (time .gt. 0) then
      lf = int(log10(time))+4
    else
      lf = 4
    end if
    if (lf .lt. 4) lf = 4
  !     time format string
    write(fmt,5) cfm(1),lf,cfm(2)
  !     buffer
    write(stime,fmt) time
  !     check size
    if (time .lt. 1) stime = blank//stime(1:)
  !     size of xtime
    lf = min(len(xtime),len_trim(stime))
    xtime = stime(1:lf)
  !
    return
  !
  5 format(a,i4,a)
  !
  end function xtime

end module rd_textfun
