[ADO] 
TimeOut=10
Provider=MSDASQL
DataSource=
Nativo=0
SubStr=%
Sub1Str=_

[ODBC]
Dsn=oraclewm
Username=adm_eng
Password=a,98:p
Admin=adm_eng.
NaoOra=0

;[ODBC]
;Dsn=access
;NaoOra=1

;[ODBC]
;Dsn=wmadmu1_desen
;Username=adm_eng
;Password=|U8+2cP
;Admin=adm_eng.
;NaoOra=0

[CONSTANTES MANCAL]
Mancais de Bucha Flangeado=1
Mancais de Bucha Pedestal=2
Mancais de Rolamento=0
Outro Valor=-1

[CAMINHOS]
Biege=q:\APPS\_EXTPACK\BIEGE\biege.exe
Entrada=c:\tmp\temp.txt
Saida=c:\tmp\Biegedat.bga
Arquivo Empuxo=c:\tmp\EINBIEGE.DAT
Command=q:\apps\_nonstd\wm_mit\fde\exec\hpgl.bat c:\tmp\Biegedat.plt
RegAdocn=Q:\apps\_nonstd\adocn\adocn.exe
FdeMit=q:\apps\_nonstd\wm_mit\fde\fdemit.exe
FdeMss=Q:\APPS\_NONSTD\WM_MS\FDE\FdeMss.exe

[CONFIGURACOES]
Altura Carga=100
Fator Escala=6
X inicial=100

[TEMPO EXCLUSAO]
Meses=-1

[TIPO SEGMENTO]
Redondo=0
Costelado=1
Oco=2

[SEGMENTO PADRAO]
Redondo=0

[conexao]
servidor=q:\apps\_nonstd\adocn\adocn.exe

[FLECHA]
PERC_LIM_DIV_SEGM=0.95
OUT=c:\tmp\IBIEGE_in2.txt
IN=c:\tmp\flecha_in.prn
REL=c:\tmp\IBIEGE_REL.txt
GPH1=c:\tmp\posicao.prn
GPH2=c:\tmp\Deflexao_vertical.prn
GPH3=c:\tmp\Deflexao_horizontal.prn
NRESC=40
EXE=Q:\APPS\_EXTPACK\BIEGE\Flecha\Flecha.exe
WAIT=180